# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tnB2u77WwP9VpfNb4jW3W08NOs40zNdi
"""

import csv
import sys

def gff_to_csv(gff_file, csv_file):
    """
    Convert a GFF file to CSV format

    Parameters:
    gff_file (str): Path to input GFF file
    csv_file (str): Path to output CSV file
    """

    # Define headers for CSV file based on GFF format
    csv_headers = ['seqid', 'source', 'type', 'start', 'end', 'score', 'strand', 'phase', 'attributes']

    # Open files
    with open(gff_file, 'r') as infile, open(csv_file, 'w', newline='') as outfile:
        # Create CSV writer
        csv_writer = csv.writer(outfile)

        # Write header
        csv_writer.writerow(csv_headers)

        # Process each line
        for line in infile:
            # Skip comments and empty lines
            if line.startswith('#') or not line.strip():
                continue

            # Split GFF fields
            fields = line.strip().split('\t')

            # Write to CSV
            csv_writer.writerow(fields)

    print(f"Conversion complete. CSV file saved to {csv_file}")

def gff_to_csv_with_attribute_parsing(gff_file, csv_file):
    """
    Convert a GFF file to CSV format with expanded attributes

    Parameters:
    gff_file (str): Path to input GFF file
    csv_file (str): Path to output CSV file
    """

    # Define basic headers
    basic_headers = ['seqid', 'source', 'type', 'start', 'end', 'score', 'strand', 'phase']

    # Set to track all attribute keys found in the file
    all_attr_keys = set()

    # First pass: identify all attribute keys
    with open(gff_file, 'r') as infile:
        for line in infile:
            if line.startswith('#') or not line.strip():
                continue

            fields = line.strip().split('\t')
            if len(fields) >= 9:
                # Parse attributes
                attr_str = fields[8]
                attr_pairs = attr_str.split(';')

                for pair in attr_pairs:
                    if '=' in pair:
                        key, _ = pair.split('=', 1)
                        all_attr_keys.add(key)

    # Convert to sorted list for consistent column order
    attr_keys = sorted(list(all_attr_keys))

    # Full headers including attributes
    csv_headers = basic_headers + attr_keys

    # Second pass: write the CSV with parsed attributes
    with open(gff_file, 'r') as infile, open(csv_file, 'w', newline='') as outfile:
        csv_writer = csv.writer(outfile)
        csv_writer.writerow(csv_headers)

        for line in infile:
            if line.startswith('#') or not line.strip():
                continue

            fields = line.strip().split('\t')
            if len(fields) < 9:
                continue  # Skip lines with insufficient fields

            # Get basic fields
            basic_values = fields[:8]

            # Parse attributes into a dictionary
            attr_dict = {}
            attr_str = fields[8]
            attr_pairs = attr_str.split(';')

            for pair in attr_pairs:
                if '=' in pair:
                    key, value = pair.split('=', 1)
                    attr_dict[key] = value

            # Create a row with basic fields and attributes
            row = basic_values + [attr_dict.get(key, '') for key in attr_keys]
            csv_writer.writerow(row)

    print(f"Conversion complete with parsed attributes. CSV file saved to {csv_file}")

# Example usage
if __name__ == "__main__":
    if len(sys.argv) < 3:
        print("Usage: python gff_to_csv.py input.gff output.csv [--parse-attributes]")
        sys.exit(1)

    gff_file = sys.argv[1]
    csv_file = sys.argv[2]

    # Check if we should parse attributes
    if len(sys.argv) > 3 and sys.argv[3] == "--parse-attributes":
        gff_to_csv_with_attribute_parsing(gff_file, csv_file)
    else:
        gff_to_csv(gff_file, csv_file)

pip install requests

import csv
import gzip
import os
import sys

def download_file(url, output_file):
    """
    Download a file from a URL and save it locally
    """
    import requests

    print(f"Downloading {url}...")
    response = requests.get(url, stream=True)
    response.raise_for_status()

    with open(output_file, 'wb') as f:
        for chunk in response.iter_content(chunk_size=8192):
            f.write(chunk)

    print(f"Downloaded to {output_file}")

def gff_to_csv(gff_file, csv_file):
    """
    Convert a GFF file to CSV format
    """
    # Determine if the file is gzipped
    is_gzipped = gff_file.endswith('.gz')
    opener = gzip.open if is_gzipped else open

    print(f"Converting {gff_file} to {csv_file}...")

    # Define CSV header fields
    fieldnames = [
        'seqid', 'source', 'type', 'start', 'end', 'score',
        'strand', 'phase', 'attributes', 'gene_name', 'product'
    ]

    with opener(gff_file, 'rt') as gff, open(csv_file, 'w', newline='') as csvfile:
        # Create CSV writer
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()

        # Process GFF file
        for line in gff:
            # Skip comment lines
            if line.startswith('#'):
                continue

            # Split the line by tabs
            fields = line.strip().split('\t')

            # Skip lines that don't have the expected number of fields
            if len(fields) != 9:
                continue

            # Parse the attributes field into a dictionary
            attributes_dict = {}
            if fields[8] != '.':
                attributes = fields[8].split(';')
                for attr in attributes:
                    if '=' in attr:
                        key, value = attr.split('=', 1)
                        attributes_dict[key] = value

            # Extract gene name and product if available
            gene_name = attributes_dict.get('Name', attributes_dict.get('gene', ''))
            product = ''

            # Look for product in attributes
            if 'product' in attributes_dict:
                product = attributes_dict['product']

            # Create row data
            row = {
                'seqid': fields[0],
                'source': fields[1],
                'type': fields[2],
                'start': fields[3],
                'end': fields[4],
                'score': fields[5],
                'strand': fields[6],
                'phase': fields[7],
                'attributes': fields[8],
                'gene_name': gene_name,
                'product': product
            }

            # Write the row to the CSV file
            writer.writerow(row)

    print(f"Conversion complete. CSV file saved as {csv_file}")

def main():
    # URLs for downloading
    fna_url = "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/845/GCF_000005845.2_ASM584v2/GCF_000005845.2_ASM584v2_genomic.fna.gz"
    gff_url = "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/845/GCF_000005845.2_ASM584v2/GCF_000005845.2_ASM584v2_genomic.gff.gz"

    # Local filenames
    fna_file = "GCF_000005845.2_ASM584v2_genomic.fna.gz"
    gff_file = "GCF_000005845.2_ASM584v2_genomic.gff.gz"
    csv_file = "GCF_000005845.2_ASM584v2_genomic.csv"

    # Download files if they don't exist
    if not os.path.exists(fna_file):
        download_file(fna_url, fna_file)
    else:
        print(f"{fna_file} already exists, skipping download")

    if not os.path.exists(gff_file):
        download_file(gff_url, gff_file)
    else:
        print(f"{gff_file} already exists, skipping download")

    # Convert GFF to CSV
    gff_to_csv(gff_file, csv_file)

    print("\nProcess completed successfully!")
    print(f"Downloaded FNA file: {fna_file}")
    print(f"Downloaded GFF file: {gff_file}")
    print(f"Created CSV file: {csv_file}")

if __name__ == "__main__":
    main()

